### ISSUE TITLE
don't have creole.xml

### ISSUE THREAD

**Issue by wjj31767** [GateNLP/gateplugin-Stanford_CoreNLP#2]
Hi,
Have you tried it on Gate 8.6 version, it can't load in and it need creole plugin.

**Comment by wjj31767** [comment]
![image](https://user-images.githubusercontent.com/44480478/72976303-a4785f00-3dd2-11ea-85d0-961b886deee6.png)

**Comment by greenwoodma** [comment]
Due to a change in the security settings of the main Maven repo you can [no longer load plugins into 8.6 without a work around](https://groups.io/g/gate-users/message/511). We have released a new version, GATE 8.6.1, that fixes this error if that is easier.

**Comment by ianroberts** [comment]
If you install 8.6.1 then you should see Stanford CoreNLP appear as an option in the plugin manager by default, and you just need to tick the "load now" box to load it - you don't need to download anything yourself.

**Comment by wjj31767** [comment]
Thanks for your so quickly reply.
I want to do some changes in stanford parser depency graph, so I want to do it in here. And I've tried 8.6.1 version in windows 10 and ubuntu, it didn't work also. I know it has plugin in the manager. But I want to build my own for integrating into the other project.

**Comment by ianroberts** [comment]
If you do really _need_ to modify the source code for your use case then I suggest you fork the plugin into your own GitHub space, clone it from there and change the `groupId` in `pom.xml`.  When you've made your changes then build your version using `mvn install` in the usual way, then load it _as a Maven plugin_ in the plugin manager, specifying the group ID, artifact ID and version as they are in _your_ `pom.xml` (so your new group ID, and probably the existing artifact ID `stanford-corenlp` and version `8.6-SNAPSHOT`).  For Maven-style plugins you have to load them by group/artifact/version rather than by pointing at the directory - GATE will look in your local cache (where `mvn install` puts things) first before it tries loading things from the internet.

However I would first question whether you do really _need_ to modify the source.  You may be able to achieve what you want by post-processing the regular output with a JAPE grammar or similar, or if you have the data to train your own model then you can point the existing parser PR at your model without needing to modify the code.
